/**
 * UI text, Russian and English.
 *
 * `Dict` is inferred from the Russian dictionary and the English one is typed
 * against it, so a key added to one and forgotten in the other is a build
 * error rather than a blank label at runtime.
 */

export const RU = {
  app: {
    name: "lil view",
    tagline: "Открой одну картинку — листай всю папку.",
    dropHint: "Перетащи сюда файл или папку",
    openBtn: "Открыть…",
    emptyKeys: "или нажми",
  },
  toolbar: {
    open: "Открыть файл или папку",
    prev: "Предыдущее",
    next: "Следующее",
    zoomOut: "Уменьшить",
    zoomIn: "Увеличить",
    fit: "Вписать в окно",
    actual: "Реальный размер",
    rotateLeft: "Повернуть влево",
    rotateRight: "Повернуть вправо",
    filmstrip: "Плёнка миниатюр",
    grid: "Сетка",
    slideshow: "Слайдшоу",
    info: "Сведения о снимке",
    fullscreen: "Во весь экран",
    settings: "Настройки",
    more: "Ещё",
    sendToImage: "Открыть в lil edit",
    sendToImageMissing: "lil edit не установлен",
  },
  status: {
    of: "из",
    noFile: "Файл не открыт",
    px: "пикс.",
  },
  info: {
    title: "Сведения",
    file: "Файл",
    name: "Имя",
    path: "Путь",
    size: "Размер",
    dimensions: "Разрешение",
    camera: "Съёмка",
    make: "Камера",
    model: "Модель",
    lens: "Объектив",
    iso: "ISO",
    exposure: "Выдержка",
    aperture: "Диафрагма",
    focal: "Фокусное",
    taken: "Снято",
    gps: "Координаты",
    none: "Метаданных нет",
    raw: "Все поля",
  },
  actions: {
    trash: "В Корзину",
    move: "Переместить в папку…",
    reveal: "Показать в Finder",
    copyPath: "Копировать путь",
    copyImage: "Копировать изображение",
    saveAs: "Сохранить как…",
    openIn: (app: string) => `Открыть в ${app}`,
    imageMissing:
      "lil edit не установлен — это соседнее приложение набора, оно умеет сжимать, убирать фон и апскейлить.",
    confirmTrash: (name: string) => `Отправить «${name}» в Корзину?`,
    trashed: (name: string) => `«${name}» — в Корзине`,
    moved: (name: string) => `«${name}» перемещён`,
    copied: "Скопировано",
    saved: (name: string) => `Сохранено: ${name}`,
    cancel: "Отмена",
    ok: "Хорошо",
  },
  settings: {
    title: "Настройки",
    back: "Назад",
    tabFiles: "Файлы",
    tabViewing: "Просмотр",
    tabLook: "Оформление",
    tabMore: "Ещё",
    appearance: "Внешний вид",
    appearanceLead: "Скин меняет весь интерфейс — цвета, шрифты, формы и анимации. Выбор запоминается.",
    appearanceHint: "Скин, светлая или тёмная тема и язык интерфейса.",
    skin: "Скин",
    chosen: "Выбран",
    mode: "Тема",
    theme: "Тема",
    language: "Язык",
    viewing: "Просмотр",
    defaultZoom: "Масштаб при открытии",
    zoomFit: "Вписать в окно",
    zoomActual: "Реальный размер",
    zoomFitLarge: "Вписать, если не влезает",
    wheel: "Колесо / свайп двумя пальцами",
    wheelPan: "Двигает снимок",
    wheelZoom: "Меняет масштаб",
    wheelHint: "Листание — только стрелками и кнопками ◀ ▶. Щипок двумя пальцами всегда меняет масштаб.",
    sort: "Порядок в папке",
    sortName: "По имени",
    sortDate: "По дате",
    sortSize: "По размеру",
    sortDesc: "В обратном порядке",
    slideshowInterval: "Интервал слайдшоу",
    seconds: "с",
    loop: "Зациклить",
    shuffle: "Вперемешку",
    cache: "Кэш превью",
    cacheHint: "Расшифрованные кадры держатся в памяти, чтобы листание было мгновенным.",
    clearCache: "Очистить",
    cleared: (mb: string) => `Освобождено ${mb} МБ`,
    about: "О программе",
    version: "Версия",
  },
  assoc: {
    title: "Открывать все изображения в lil view",
    hint:
      "macOS хранит приложение по умолчанию отдельно для каждого типа файла. " +
      "Кнопка проходит по всем графическим типам сразу и потом перечитывает " +
      "их у системы — в списке видно, что реально применилось.",
    apply: "Сделать приложением по умолчанию",
    applying: "Применяем…",
    restore: "Вернуть как было",
    refresh: "Проверить ещё раз",
    score: (ok: number, total: number) => `${ok} из ${total} типов`,
    notInstalled:
      "Приложение запущено не из папки «Программы». macOS запоминает ассоциации " +
      "по конкретной копии — перенесите lil view в «Программы» и нажмите снова.",
    unbundled: "Сборка запущена не как .app — соберите приложение и запустите его.",
    unknownHandler: "нет обработчика",
    weAre: "lil view",
  },
  appUpdate: {
    current: "Установлена",
    check: "Проверить обновления",
    checking: "Проверяем…",
    upToDate: "Свежая версия, обновлять нечего.",
    failed: "Не вышло спросить GitHub — похоже, нет сети.",
    available: (v: string) => `Вышла ${v}`,
    notes: "Что изменилось",
    download: "Скачать",
    auto: "Проверять при запуске",
    autoNote: "Это единственное соединение, которое приложение открывает само. Выключишь — не откроет ни одного, пока не попросишь.",
  },
  mode: {
    light: "Светлая",
    dark: "Тёмная",
    toLightTitle: "Светлая тема",
    toDarkTitle: "Тёмная тема",
    toLightAria: "Переключить на светлую тему",
    toDarkAria: "Переключить на тёмную тему",
  },
  lang: {
    label: "Язык",
    ru: "Русский",
    en: "English",
  },
  skins: {
    studio: { name: "lil studio" },
    brutal: { name: "Нео-брутализм" },
    riso: { name: "Рисо-поп" },
    te: { name: "Девайс" },
  },
  errors: {
    open: "Не удалось открыть",
    decode: "Не удалось показать этот файл",
    empty: "В папке нет изображений",
  },
};

export type Dict = typeof RU;

export const EN: Dict = {
  app: {
    name: "lil view",
    tagline: "Open one picture — page through the whole folder.",
    dropHint: "Drop a file or a folder here",
    openBtn: "Open…",
    emptyKeys: "or press",
  },
  toolbar: {
    open: "Open a file or folder",
    prev: "Previous",
    next: "Next",
    zoomOut: "Zoom out",
    zoomIn: "Zoom in",
    fit: "Fit to window",
    actual: "Actual size",
    rotateLeft: "Rotate left",
    rotateRight: "Rotate right",
    filmstrip: "Filmstrip",
    grid: "Grid",
    slideshow: "Slideshow",
    info: "Photo info",
    fullscreen: "Fullscreen",
    settings: "Settings",
    more: "More",
    sendToImage: "Open in lil edit",
    sendToImageMissing: "lil edit isn’t installed",
  },
  status: {
    of: "of",
    noFile: "No file open",
    px: "px",
  },
  info: {
    title: "Info",
    file: "File",
    name: "Name",
    path: "Path",
    size: "Size",
    dimensions: "Dimensions",
    camera: "Capture",
    make: "Camera",
    model: "Model",
    lens: "Lens",
    iso: "ISO",
    exposure: "Shutter",
    aperture: "Aperture",
    focal: "Focal length",
    taken: "Taken",
    gps: "Coordinates",
    none: "No metadata",
    raw: "All fields",
  },
  actions: {
    trash: "Move to Trash",
    move: "Move to folder…",
    reveal: "Reveal in Finder",
    copyPath: "Copy path",
    copyImage: "Copy image",
    saveAs: "Save as…",
    openIn: (app: string) => `Open in ${app}`,
    imageMissing:
      "lil edit isn’t installed — it’s the sibling app that compresses, removes backgrounds and upscales.",
    confirmTrash: (name: string) => `Move “${name}” to the Trash?`,
    trashed: (name: string) => `“${name}” moved to the Trash`,
    moved: (name: string) => `“${name}” moved`,
    copied: "Copied",
    saved: (name: string) => `Saved: ${name}`,
    cancel: "Cancel",
    ok: "OK",
  },
  settings: {
    title: "Settings",
    back: "Back",
    tabFiles: "Files",
    tabViewing: "Viewing",
    tabLook: "Appearance",
    tabMore: "More",
    appearance: "Appearance",
    appearanceLead: "A skin changes the whole interface — colours, fonts, shapes and animation. Your choice is remembered.",
    appearanceHint: "Skin, light or dark, and interface language.",
    skin: "Skin",
    chosen: "Selected",
    mode: "Theme",
    theme: "Theme",
    language: "Language",
    viewing: "Viewing",
    defaultZoom: "Zoom on open",
    zoomFit: "Fit to window",
    zoomActual: "Actual size",
    zoomFitLarge: "Fit only if too large",
    wheel: "Wheel / two-finger swipe",
    wheelPan: "Pans the image",
    wheelZoom: "Zooms",
    wheelHint: "Paging is on the arrow keys and the ◀ ▶ buttons only. Pinch always zooms.",
    sort: "Folder order",
    sortName: "By name",
    sortDate: "By date",
    sortSize: "By size",
    sortDesc: "Reversed",
    slideshowInterval: "Slideshow interval",
    seconds: "s",
    loop: "Loop",
    shuffle: "Shuffle",
    cache: "Preview cache",
    cacheHint: "Decoded frames stay in memory so paging back is instant.",
    clearCache: "Clear",
    cleared: (mb: string) => `Freed ${mb} MB`,
    about: "About",
    version: "Version",
  },
  assoc: {
    title: "Open every image in lil view",
    hint:
      "macOS stores the default app separately for each file type. This button " +
      "walks all image types at once, then reads them back from the system — " +
      "the list below shows what actually took effect.",
    apply: "Make it the default",
    applying: "Applying…",
    restore: "Restore previous",
    refresh: "Check again",
    score: (ok: number, total: number) => `${ok} of ${total} types`,
    notInstalled:
      "The app isn’t running from /Applications. macOS ties associations to a " +
      "specific copy — move lil view to Applications and press again.",
    unbundled: "Running unbundled — build the .app and launch that.",
    unknownHandler: "no handler",
    weAre: "lil view",
  },
  appUpdate: {
    current: "Installed",
    check: "Check for updates",
    checking: "Checking…",
    upToDate: "Up to date — nothing to install.",
    failed: "Couldn't reach GitHub — looks like there's no network.",
    available: (v: string) => `${v} is out`,
    notes: "What changed",
    download: "Download",
    auto: "Check on launch",
    autoNote: "This is the only connection the app opens on its own. Turn it off and it opens none until you ask.",
  },
  mode: {
    light: "Light",
    dark: "Dark",
    toLightTitle: "Light theme",
    toDarkTitle: "Dark theme",
    toLightAria: "Switch to the light theme",
    toDarkAria: "Switch to the dark theme",
  },
  lang: {
    label: "Language",
    ru: "Русский",
    en: "English",
  },
  skins: {
    studio: { name: "lil studio" },
    brutal: { name: "Neo-brutalism" },
    riso: { name: "Riso-pop" },
    te: { name: "Device" },
  },
  errors: {
    open: "Couldn’t open",
    decode: "Couldn’t display this file",
    empty: "No images in this folder",
  },
};

export const DICTS = { ru: RU, en: EN } as const;
